name = "huge-mdl"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Material Design Lite For Hugo"
homepage = "//github.com/digitalcraftsman/hugo-steam-theme"
tags = ["google analytics", "google plus", "disqus", "ghost", "blog", "minimal", "custom themes", "single column"]
features = ["", ""]
min_version = 0.14

[author]
  name = "Sam C."
  homepage = "//github.com/samrocksc/"
